@startuml
actor User
boundary "Package Page" as Client
participant "<<middlewares>>\ngetAuth" as mid1
participant "<<middlewares>>\ncheckPermission" as mid2
participant "<<action>>\ndelete" as Controller
entity "Package" as Model
database "MySQL" as DB

User -> Client: select package
activate User
activate Client
Client -> mid1: DELETE package/delete
activate mid1
alt invalid token
    mid1 --> Client: message, 401
end
alt User not exist
    mid1 --> Client: message, 401
end
mid1 -> mid2: next()
deactivate mid1
activate mid2
alt API not found
    mid2 --> Client: message, 404
end
alt Permission denied
    mid2 --> Client: message, 403
end
mid2 -> Controller: next()
deactivate mid2
activate Controller
Controller -> Model: deleteOne()
activate Model
Model -> DB: deleteOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller --> Client: message, 200
deactivate Controller







deactivate Client

@enduml
