@startuml
actor User
boundary "Package Page" as Client
participant "<<middlewares>>\ngetAuth" as mid1
participant "<<middlewares>>\ncheckPermission" as mid2
participant "<<action>>\nget" as Controller
entity "Package" as Model
database "MySQL" as DB

User -> Client: type in package information
activate User
activate Client
Client -> mid1: POST /package/update
activate mid1
alt invalid token
    mid1 --> Client: message, 401
end
alt User not exist
    mid1 --> Client: message, 401
end
mid1 -> mid2: next()
deactivate mid1
activate mid2
alt API not found
    mid2 --> Client: message, 404
end
alt Permission denied
    mid2 --> Client: message, 403
end
mid2 -> Controller: next()
deactivate mid2
activate Controller
Controller -> Model: find()
activate Model
Model -> DB: find()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Alt Package not found
    Controller --> Client: message, 404
end
Controller -> Model: updateOne()
activate Model
Model -> DB: updateOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
alt Package title duplicated
Controller --> Client: message, 400
end
Controller --> Client: message, 200
deactivate Controller







deactivate Client

@enduml
