@startuml
actor User
boundary "Profile Page" as Client
participant "<<middlewares>>\ngetAuth" as mid1
participant "<<middlewares>>\ncheckPermission" as mid2
participant "<<action>>\nchange" as Controller
entity "Auth" as Model
database "MySQL" as DB

User -> Client: Type in old and new password
activate User
activate Client
Client -> mid1: POST /auth/change
activate mid1
opt invalid token
    mid1 --> Client: message, 401
end
opt User not exist
    mid1 --> Client: message, 401
end
mid1 -> mid2: next()
deactivate mid1
activate mid2
opt API not found
    mid2 --> Client: message, 404
end
opt Permission denied
    mid2 --> Client: message, 403
end
mid2 -> Controller: next()
deactivate mid2
activate Controller
Controller -> Model: find()
activate Model
Model -> DB: find()
activate DB
DB --> Model
deactivate DB
Model --> Controller: auth entity
deactivate Model
opt No matching email found
    Controller --> Client: message, 404
end
opt Old password is incorrect
    Controller --> Client: message, 400
end
Controller -> Model: updateOne()
activate Model
Model -> DB: updateOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller --> Client: message, 200
deactivate Controller
    
deactivate Client




@enduml
