@startuml
actor User
boundary "Forgot Page" as Client
participant "<<action>>\nforgotPass" as Controller
entity "Auth" as Model
database "MySQL" as DB

User -> Client: Type in old and new password
activate User
activate Client

Client -> Controller: POST /forgotPass
activate Controller
Controller -> Model: find()
activate Model
Model -> DB: find()
activate DB
DB --> Model
deactivate DB
Model --> Controller: auth entity
deactivate Model
alt No matching email found
    Controller --> Client: message, 404
end
Controller -> Controller: Compare Password
alt Old password is incorrect
    Controller --> Client: message, 400
end
Controller -> Controller: Hash password
Controller -> Model: updateOne()
activate Model
Model -> DB: updateOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller --> Client: message, 200
deactivate Controller
    
deactivate Client




@enduml
