@startuml
actor User
boundary "Forgot Page" as Client
participant "<<action>>\nforgotPass" as Controller
participant "<<service>>\nNodemailer" as mail
entity "Auth" as Model
database "MySQL" as DB

User -> Client: Type in email
activate User
activate Client

Client -> Controller: POST /forgotPass
activate Controller
Controller -> Model: find()
activate Model
Model -> DB: find()
activate DB
DB --> Model
deactivate DB
Model --> Controller: auth entity
deactivate Model
alt No matching email found
    Controller --> Client: message, 404
end
Controller -> Model: updateOne(otp)
activate Model
Model -> DB: updateOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller -> mail: sendMail()
activate mail
deactivate mail
Controller --> Client: message, 200
deactivate Controller
    
deactivate Client




@enduml
