@startuml
actor User
boundary "Reset Page" as Client
participant "<<action>>\nResetPass" as Controller
entity "Auth" as Model
database "MySQL" as DB

User -> Client: Type in otp
activate User
activate Client

Client -> Controller: POST /resetPass
activate Controller
Controller -> Model: find()
activate Model
Model -> DB: find()
activate DB
DB --> Model
deactivate DB
Model --> Controller: auth entity
deactivate Model
Controller -> Controller: verify OTP
alt OTP code is invalid
    Controller --> Client: message, 403
end
Controller -> Controller: verify expired Date
alt OTP code is expired
    Controller --> Client: message, 403
end
Controller -> Controller: hash password
Controller -> Model: updateOne(newPassword)
activate Model
Model -> DB: updateOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller --> Client: message, 200
deactivate Controller
    
deactivate Client




@enduml
