@startuml
actor User
boundary "BlackList Page" as Client
participant "<<middlewares>>\ngetAuth" as mid1
participant "<<middlewares>>\ncheckPermission" as mid2
participant "<<action>>\nget" as Controller
entity "BlackList" as Model
database "MySQL" as DB

User -> Client: edit blacklist information
activate User
activate Client
Client -> mid1: POST /blacklist/create
activate mid1
alt invalid token
    mid1 --> Client: message, 401
end
alt User not exist
    mid1 --> Client: message, 401
end
mid1 -> mid2: next()
deactivate mid1
activate mid2
alt API not found
    mid2 --> Client: message, 404
end
alt Permission denied
    mid2 --> Client: message, 403
end
mid2 -> Controller: next()
deactivate mid2
activate Controller
Controller -> Model: create()
activate Model
Model -> DB: create()
activate DB
DB --> Model
deactivate DB
Model --> Controller
deactivate Model
Controller --> Client: message, 201
deactivate Controller







deactivate Client

@enduml
