@startuml
actor User
boundary "Profile Page" as Client
participant "<<middlewares>>\ngetAuth" as mid1
participant "<<action>>\ngetUserInfo" as Controller
entity "User" as Model
database "MySQL" as DB

User -> Client:Access profile page
activate User
activate Client
Client -> mid1: GET /user?id=1
activate mid1
alt invalid token
    mid1 --> Client: message, 401
end
alt User not exist
    mid1 --> Client: message, 401
end
mid1 -> Controller: next()
deactivate mid1
activate Controller
Controller -> Model: findOne()
activate Model
Model -> DB: findOne()
activate DB
DB --> Model
deactivate DB
Model --> Controller: User info
deactivate Model

Controller --> Client: message, data, 200
deactivate Controller







deactivate Client

@enduml
